// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmql_72LIZvC9hU_6AAbiHrMR8fmYJ0Wc',
    appId: '1:1026695506439:web:0a4d2c2b150ecb993c58a2',
    messagingSenderId: '1026695506439',
    projectId: 'ssm-sb',
    authDomain: 'ssm-sb.firebaseapp.com',
    storageBucket: 'ssm-sb.firebasestorage.app',
    measurementId: 'G-06LEG3BW61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEnGG1az7ISAKW-wpi82F2XoG9gBi4XUI',
    appId: '1:1026695506439:android:773e7bf1172aa60d3c58a2',
    messagingSenderId: '1026695506439',
    projectId: 'ssm-sb',
    storageBucket: 'ssm-sb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoRZj0uWY6EFLcNAHlD2JHhnO7TkI6Yac',
    appId: '1:1026695506439:ios:4a2e44328bd7ce6f3c58a2',
    messagingSenderId: '1026695506439',
    projectId: 'ssm-sb',
    storageBucket: 'ssm-sb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoRZj0uWY6EFLcNAHlD2JHhnO7TkI6Yac',
    appId: '1:1026695506439:ios:4a2e44328bd7ce6f3c58a2',
    messagingSenderId: '1026695506439',
    projectId: 'ssm-sb',
    storageBucket: 'ssm-sb.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmql_72LIZvC9hU_6AAbiHrMR8fmYJ0Wc',
    appId: '1:1026695506439:web:aef20fa0ecc181dd3c58a2',
    messagingSenderId: '1026695506439',
    projectId: 'ssm-sb',
    authDomain: 'ssm-sb.firebaseapp.com',
    storageBucket: 'ssm-sb.firebasestorage.app',
    measurementId: 'G-CZF6HNQER7',
  );
}

class DashboardFirebaseOptions {
  // Keep false by default for safe local demos. Enable with:
  // flutter run --dart-define=ENABLE_FIREBASE=true
  static const bool enabled = bool.fromEnvironment(
    'ENABLE_FIREBASE',
    defaultValue: false,
  );

  static FirebaseOptions get currentPlatform =>
      DefaultFirebaseOptions.currentPlatform;
}
