name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # INSTALL FLUTTER
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # ENABLE WEB SUPPORT
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # INSTALL DEPENDENCIES
      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      # INJECT GOOGLE MAPS KEY
      - name: Inject Google Maps API Key
        run: sed -i 's|YOUR_API_KEY_HERE|${{ secrets.GOOGLE_MAPS_API_KEY }}|g' frontend/web/index.html

      # BUILD
      - name: Build Flutter Web
        working-directory: frontend
        run: flutter build web

      # DEPLOY
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SSM_SB }}
          channelId: live
          projectId: ssm-sb