name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # INSTALL FLUTTER
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # ENABLE WEB
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # DEPENDENCIES
      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      # INJECT KEY
      - name: Inject Google Maps API Key
        run: sed -i 's|YOUR_API_KEY_HERE|${{ secrets.GOOGLE_MAPS_API_KEY }}|g' frontend/web/index.html

      # BUILD
      - name: Build Flutter Web
        working-directory: frontend
        run: flutter build web

      # DEPLOY PREVIEW
      - name: Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SSM_SB }}
          projectId: ssm-sb